package com.sprintqa.class47;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LoginTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\lanar\\eclipse-workspace\\" + "SeleniumExamples\\webdrivers\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void loginTest() {

		// Test name: Login Test
		// Step # | name | target | value | comment
		// 1 | open | / | |
		driver.get("http://skookii.com/");
		// 2 | setWindowSize | 1280x877 | |
		driver.manage().window().setSize(new Dimension(1280, 877));
		// 3 | click | linkText=LOG IN | |
		driver.findElement(By.linkText("LOG IN")).click();
		// 4 | click | name=username | |
		driver.findElement(By.name("username")).click();
		// 5 | type | name=username | ali@skookii.com |
		driver.findElement(By.name("username")).sendKeys("ali@skookii.com");
		// 6 | click | name=password | |
		driver.findElement(By.name("password")).click();
		// 7 | type | name=password | 87654321 |
		driver.findElement(By.name("password")).sendKeys("87654321");
		// 8 | click | css=.btn > span:nth-child(1) | |
		driver.findElement(By.cssSelector(".btn > span:nth-child(1)")).click();
		// 9 | click | css=.hidden-xs | |
		driver.findElement(By.cssSelector(".hidden-xs")).click();
		// 10 | click | linkText=Log Out | |
		driver.findElement(By.linkText("Log Out")).click();
	}
}
