package com.sprintqa.class48;

import java.util.HashMap;
import java.util.Map;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 * In this example we are converting a Selenium IDE exported JUnit test to use
 * WebDriver. We are also changing the WebDriver configuration to use Chrome.
 * Then we walk through some ways of navigating with the WebDriver class.
 * 
 * @author mpmeloche
 *
 */
public class WebDriverExampleTest {

	// Declare Class Variables Here
	static private WebDriver driver;
	static private Map<String, Object> vars;
	static JavascriptExecutor js;

	/**
	 * Remember to configure your System path so the application can find your
	 * ChromeDriver binary files.
	 * 
	 * @throws Exception
	 */
	@BeforeAll
	static void setUp() {
		// Setup the System path to the Selenium Chrome Binary file
		// Use System.getProperty("user.dir") to get the system path for the project.
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/webdrivers/mac/chromedriver");

		// Instantiate WebDriver to use ChromeDriver.
		driver = new ChromeDriver();

		/*
		 * Setup and load Webdriver for Firefox
		 * System.setProperty("webdriver.chrome.driver",
		 * "/Users/mpmeloche/Development/eclipse/workspace/SeleniumExamples/webdrivers/geckodriver"
		 * ); driver = new FirefoxDriver();
		 */

		// This is necessary if we want to execute any JavaScript commands
		js = (JavascriptExecutor) driver;

		// This is used to load test data
		vars = new HashMap<String, Object>();
	}

	/**
	 * Make sure when your done running your tests that you close the window/tab and
	 * then exit out of the browser window.
	 * 
	 * @throws Exception
	 */
	@AfterAll
	static void tearDown() {
		driver.close();
		driver.quit();
	}

	/**
	 * Connect to skookii.com and navigate around the web site.
	 */
	@Test
	@DisplayName(value = "WebDriver Test")
	void loginTest() {
		// 1 | open browser with WebDriver | / | |
		driver.get("http://skookii.com/");

		// 2 | setWindowSize | 1280x877 | |
		driver.manage().window().setSize(new Dimension(1280, 877));

		// 3 | Change page to about us through location bar
		driver.navigate().to("http://skookii.com/about-skookii/");

		// 4 | Refresh the page
		driver.navigate().refresh();

		// 5 | Verify what page the driver is on
		String url = driver.getCurrentUrl();
		System.out.println(url);

		// 6 | Click the browsers back button
		driver.navigate().back();

		url = driver.getCurrentUrl();
		System.out.println(url);

		// 7 | Click the browsers forward button
		driver.navigate().forward();

		url = driver.getCurrentUrl();
		System.out.println(url);

		// 8| get the page title
		String title = driver.getTitle();
		System.out.println(title);
	}
}
