package com.sprintqa.class48;

import java.util.Map;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 * Here is an Example using WebElements to input and control the HTML page
 * Elements in a web page.
 * 
 * @author mpmeloche
 *
 */
public class WebElementExampleTest {
	static private WebDriver driver;
	static private Map<String, Object> vars;
	static JavascriptExecutor js;

	/**
	 * Remember to configure your System path so the application can find your
	 * ChromeDriver binary files.
	 * 
	 * @throws Exception
	 */
	@BeforeAll
	static void setUp() {
		// Setup the System path to the Selenium Chrome Binary file
		// Use System.getProperty("user.dir") to get the system path for the project.
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/webdrivers/mac/chromedriver");

		// Instantiate WebDriver to use ChromeDriver.
		driver = new ChromeDriver();
	}

	/**
	 * Make sure when your done running your tests that you close the window/tab and
	 * then exit out of the browser window.
	 * 
	 * @throws Exception
	 */
	@AfterAll
	static void tearDown() {
		driver.close();
		driver.quit();
	}

	/**
	 * Test login functionality on saucedemo.com
	 */
	@Test
	@DisplayName(value = "WebDriver Test")
	public void loginTest() {
		// 1 | open browser with WebDriver | / | |
		driver.get("https://www.saucedemo.com/");

		// 2 | setWindowSize | 1280x877 | |
		driver.manage().window().setSize(new Dimension(1280, 877));

		// 4 | click | name=username | |
		WebElement nameElement = driver.findElement(By.id("user-name"));
		nameElement.click();

		// 5 | input text into username
		nameElement.sendKeys("standard_user");

		// 6 | click | name=password | |
		WebElement password = driver.findElement(By.id("password"));
		password.click();

		// 7 | type | name=password | 87654321 |

		password.sendKeys("secret_sauce");
		// 8 | click | css=.btn > span:nth-child(1) | |

		// 10 | click | linkText=Log Out | |
		driver.findElement(By.tagName("form")).submit();
	}
}
